### ISSUE TITLE
Null pointer exception at COMPLEX_EXPRESSION, REDUNDANT_SEMICOLON, WRONG_NEWLINES (at Fix mode)

### ISSUE THREAD

**Issue by akuleshov7** [diktat-static-analysis/diKTat#1092] opened 2021-11-07 10:55 UTC
```
package io.reflekt.plugin

import com.google.auto.service.AutoService
import io.reflekt.util.Util.DEPENDENCY_JAR_OPTION_INFO
import io.reflekt.util.Util.ENABLED_OPTION_INFO
import io.reflekt.util.Util.INTROSPECT_FILE_OPTION_INFO
import io.reflekt.util.Util.OUTPUT_DIR_OPTION_INFO
import io.reflekt.util.Util.PLUGIN_ID
import io.reflekt.plugin.utils.Keys
import org.jetbrains.kotlin.compiler.plugin.AbstractCliOption
import org.jetbrains.kotlin.compiler.plugin.CliOption
import org.jetbrains.kotlin.compiler.plugin.CommandLineProcessor
import org.jetbrains.kotlin.config.CompilerConfiguration
import org.jetbrains.kotlin.config.CompilerConfigurationKey
import java.io.File

@AutoService(CommandLineProcessor::class)
class ReflektCommandLineProcessor : CommandLineProcessor {
    /**
     * Just needs to be consistent with the key for ReflektSubPlugin#getCompilerPluginId
     */
    override val pluginId: String = PLUGIN_ID

    /**
     * Should match up with the options we return from our ReflektSubPlugin.
     * Should also have matching when branches for each name in the [processOption] function below
     */
    override val pluginOptions: Collection<CliOption> = listOf(ENABLED_OPTION, DEPENDENCY_JAR_OPTION, INTROSPECT_FILE_OPTION, OUTPUT_DIR_OPTION)

    override fun processOption(
        option: AbstractCliOption,
        value: String,
        configuration: CompilerConfiguration
    ) {
        return when (option) {
            ENABLED_OPTION -> configuration.put(Keys.ENABLED, value.toBoolean())
            DEPENDENCY_JAR_OPTION -> configuration.addToList(Keys.DEPENDENCY_JARS, File(value))
            INTROSPECT_FILE_OPTION -> configuration.addToList(Keys.INTROSPECT_FILES, File(value))
            OUTPUT_DIR_OPTION -> configuration.put(Keys.OUTPUT_DIR, File(value))
            else -> error("Unexpected config option ${option.optionName}")
        }
    }

    companion object {
        val ENABLED_OPTION =
            CliOption(
                optionName = ENABLED_OPTION_INFO.name,
                valueDescription = ENABLED_OPTION_INFO.valueDescription,
                description = ENABLED_OPTION_INFO.description
            )

        val DEPENDENCY_JAR_OPTION =
            CliOption(
                optionName = DEPENDENCY_JAR_OPTION_INFO.name,
                valueDescription = DEPENDENCY_JAR_OPTION_INFO.valueDescription,
                description = DEPENDENCY_JAR_OPTION_INFO.description,
                allowMultipleOccurrences = true,
                required = false
            )

        val INTROSPECT_FILE_OPTION =
            CliOption(
                optionName = INTROSPECT_FILE_OPTION_INFO.name,
                valueDescription = INTROSPECT_FILE_OPTION_INFO.valueDescription,
                description = INTROSPECT_FILE_OPTION_INFO.description,
                allowMultipleOccurrences = true,
                required = false
            )

        val OUTPUT_DIR_OPTION =
            CliOption(
                optionName = OUTPUT_DIR_OPTION_INFO.name,
                valueDescription = OUTPUT_DIR_OPTION_INFO.valueDescription,
                description = OUTPUT_DIR_OPTION_INFO.description,
                required = false,
                allowMultipleOccurrences = false
            )
    }

    private fun <T> CompilerConfiguration.addToList(configurationKey: CompilerConfigurationKey<List<T>>, value: T) {
        val values = get(configurationKey) ?: emptyList()
        put(configurationKey, values + value)
    }
}
```

```
[ERROR] 2021-11-07 13:44:19 Internal error has occurred in rule [newlines]. Please make an issue on this bug at https://github.com/cqfn/diKTat/.
                       As a workaround you can disable these inspections in yml config: <[COMPLEX_EXPRESSION, REDUNDANT_SEMICOLON, WRONG_NEWLINES]>.
                       Root cause of the problem is in [D:\reflekt\reflekt-plugin\src\main\kotlin\io\reflekt\plugin\ReflektCommandLineProcessor.kt] file.
java.lang.NullPointerException
        at org.cqfn.diktat.ruleset.rules.chapter3.files.NewlinesRule$handleReturnStatement$3$1.invoke(NewlinesRule.kt:340)
        at org.cqfn.diktat.ruleset.rules.chapter3.files.NewlinesRule$handleReturnStatement$3$1.invoke(NewlinesRule.kt:336)
        at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix(Warnings.kt:260)
        at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix$default(Warnings.kt:202)
        at org.cqfn.diktat.ruleset.rules.chapter3.files.NewlinesRule.handleReturnStatement(NewlinesRule.kt:335)
        at org.cqfn.diktat.ruleset.rules.chapter3.files.NewlinesRule.logic(NewlinesRule.kt:131)
        at org.cqfn.diktat.ruleset.rules.DiktatRule.visit(DiktatRule.kt:50)
        at com.pinterest.ktlint.core.KtLint$format$1.invoke(KtLint.kt:271)
```

**Comment by kgevorkyan** [comment] 2021-11-08 10:04
Can't reproduce with latest version of diktat (snapshot), seems it is already fixed by previous PR's

**Closed by kgevorkyan** 2021-11-08 10:04 UTC
Labels: bug
